### PR TITLE
chore: bump package version

### PR DESCRIPTION
**Pull request by khvn26**

### CODE REVIEW

**Review by novakzaballa — APPROVED** [review]
LGTM

**Comment by PrettyWood** [comment]
Could we have https://github.com/Flagsmith/flagsmith-python-client/pull/68 in 3.4.1 ?

**Comment by khvn26** [comment]
Skipping in favour of the 3.5.0 release (#69).

**Comment by PrettyWood** [comment]
Great thank you so much 🙏

**Pull request closed without merging**
